// ── Shared signal model + DB→MobileSignal mapping ────────────────────────────
// Single source of truth so both the detailed chart WebView (chart-view.tsx) and
// the Market/Signals screens (via hooks/use-market-data.ts) map server rows the
// same way. Keep in sync with the PC's SignalsPanel scoring (LEARNINGS rule).

export type OutcomeResult = { outcome: 'Win' | 'Loss' | 'Open'; tpHit: 1 | 2 | null; points: number | null };

export interface MobileSignal {
  time: number;
  direction: 'Long' | 'Short';
  riskLevel: 'safeplus' | 'safe' | 'risky' | 'riskiest';
  price: number;
  tp1: number;
  tp2: number;
  sl: number;
  outcome: 'Win' | 'Loss' | 'Open';
  tpHit: 1 | 2 | null;
  points: number | null;
  rth: boolean;
  /** Signal source — "vector-side-entry" marks the take-every-side-entry Long (allowed in ETH). */
  signalType: string | null;
  /** Pre-computed outcomes for each exit strategy (avoids needing candle data later). */
  exitOutcomes: Record<string, OutcomeResult & { tp1: number; tp2: number; sl: number }>;
  /** Which strategies contributed points to this signal. */
  strategies: { fp: boolean; milk: boolean; vec: boolean; milkPts: number };
}

// DST-safe RTH check — matches trading-utils.ts isRTH() exactly.
// Old versions used hardcoded UTC offsets which broke in winter (EST=UTC-5 vs
// EDT=UTC-4), ending RTH at 3 PM ET instead of 4 PM from Nov–Mar.
const _nyRthFmt = new Intl.DateTimeFormat('en-US', {
  timeZone: 'America/New_York',
  weekday: 'short', hour: '2-digit', minute: '2-digit', hour12: false,
});
export function isRTH(ts: number): boolean {
  const parts = _nyRthFmt.formatToParts(new Date(ts * 1000));
  const day  = parts.find(p => p.type === 'weekday')?.value ?? '';
  const hour = parseInt(parts.find(p => p.type === 'hour')?.value  ?? '0');
  const min  = parseInt(parts.find(p => p.type === 'minute')?.value ?? '0');
  if (day === 'Sat' || day === 'Sun') return false;
  const etMins = hour * 60 + min;
  return etMins >= 9 * 60 + 30 && etMins < 17 * 60; // 9:30 AM – 5:00 PM ET
}

function safeParse(json: any): any {
  if (!json || typeof json !== 'string') return null;
  try { return JSON.parse(json); } catch { return null; }
}

// Converts a DB row (from /api/signals/history) to MobileSignal.
export function mapDbSignal(s: any): MobileSignal {
  const isLong = s.direction === 'Long';
  const isTp2  = s.outcome === 'win_tp2'  || s.outcome === 'tp2';
  const isTp1  = s.outcome === 'win_tp1'  || s.outcome === 'win_trailer' || s.outcome === 'tp1';
  const isLoss = s.outcome === 'loss'     || s.outcome === 'sl';
  const pts    = isTp2  ? (isLong ? s.tp2 - s.entry : s.entry - s.tp2)
               : isTp1  ? (isLong ? s.tp1 - s.entry : s.entry - s.tp1)
               : isLoss ? (isLong ? s.sl  - s.entry : s.entry - s.sl)
               : null;

  // ── Confirmation breakdown — exact mirror of the PC's scoring ────────────────
  // New rows carry `confirmations` (JSON {milkOk, milkPts, vecOk, secondaryVecOk}).
  // Legacy rows fall back to safe defaults derived from the tier:
  //   • Vector is a HARD prerequisite for every persisted confluence signal → vec=true.
  //   • SAFE / SAFE+ tiers always require a milk-zone confirmation on the PC.
  const conf = safeParse(s.confirmations);
  const fpr  = safeParse(s.footprintReading);
  const isSafeTier = s.riskLevel === 'safe' || s.riskLevel === 'safeplus';
  const milk    = conf ? !!conf.milkOk : isSafeTier;
  const milkPts = conf && typeof conf.milkPts === 'number' ? conf.milkPts : (milk ? 3 : 0);
  const vec     = conf ? conf.vecOk !== false : true;
  // Footprint "fires" when the reading confirmed or partially confirmed and wasn't vetoed.
  const fp      = !!fpr && fpr.vetoed !== true && (fpr.confirmed === true || fpr.partial === true);

  return {
    time:         s.timestamp,
    direction:    s.direction,
    // SINGLE-TIER: the PC relabels every displayed signal "SAFE" (mapSignal in useTerminalData
    // hardcodes tier:"SAFE"). Mirror that so the phone never shows RISKY/RISKIEST tiers.
    // (isSafeTier above still reads the ORIGINAL s.riskLevel for milk-confirmation inference.)
    riskLevel:    'safe',
    price:        s.entry,
    tp1:          s.tp1,
    tp2:          s.tp2,
    sl:           s.sl,
    outcome:      (isTp2 || isTp1) ? 'Win' : isLoss ? 'Loss' : 'Open',
    tpHit:        isTp2 ? 2 : isTp1 ? 1 : null,
    points:       pts !== null ? +pts.toFixed(2) : null,
    rth:          isRTH(s.timestamp),
    signalType:   s.signalType ?? null,
    exitOutcomes: {},
    strategies:   { fp, milk, vec, milkPts },
  } as MobileSignal;
}

// Every row in signal_history was generated by the PC engine. Show all of them
// so the phone matches the PC exactly — the user's tier filter in signals.tsx
// handles safe/risky/riskiest display preferences at the UI level.
export function isPcDisplaySignal(_s: any): boolean {
  return true;
}
