// shared/quality-gate.ts
// ═════════════════════════════════════════════════════════════════════════════
// GENERATED FILE — regenerated by `npx tsx scripts/fact-engine-backtest.ts` on every full
// backtest run. Hand edits to the DATA below will be overwritten; the interfaces and
// functions are part of the template in the harness (edit them THERE).
//
// THE QUALITY GATE (user directive 2026-07-14: "Quality over quantity — I don't need a
// million trades, I need trades that will win"). A setup CLASS is signalType × primary
// interval. Verdicts are TWO-STAGE WALK-FORWARD (2026-07-17): the reporting window (the
// last ~3 months — user directive 2026-07-15) is split at its calendar midpoint; per-class
// MC exits are derived on the FIRST half's trades only, and each class is judged on the
// HELD-OUT second half simulated under those exits (exits never see the trades they are
// judged on). A class may fire live ONLY if its held-out half clears ITS OWN interval's
// bar (PER-INTERVAL GATE BARS — user-chosen 2026-07-31 from the per-interval gate-bar
// menu, scripts/gate-bar-menu-by-interval.ts):
//     1m   profit factor >= 2     AND expectancy > 5 pts per trade
//     5m   profit factor >= 1.75  AND expectancy > 4 pts per trade
//     15m  profit factor >= 1.75  AND expectancy > 4 pts per trade
//     60m  profit factor >= 1.5   AND expectancy > 3 pts per trade
// (Per-class n/pf/expectancy below are the HELD-OUT stats; each note records the
// first-half exits used. The exitByClass calibration shipped below is refit on the FULL
// window — future live trades are unseen data; only the verdict must be held-out.)
//
// VERDICT BASIS IS GROSS POINTS (2026-08-02 friction note): all pf/expectancy figures here
// are GROSS — no slippage or commission charged. The harness now REPORTS net-of-friction
// (~0.996 pts/round trip: 0.5 pt = one tick each side + spread allowance, plus 2 x
// $1.24 commission at $5/pt) alongside gross everywhere, and prints a FRICTION AUDIT of
// allowed classes/combos that would FAIL their bar net-of-friction — but changing the
// VERDICT basis silently is out of scope; moving the bar to net accounting is a USER call.
// Overrides:
//   • >=3 COUNTED agreeing facts fire on ANY interval/session (multi-fact pool:
//     n=2369 PF=2.031 expectancy=8.393).
//   • Classes with NO backtest data are NEVER blocked ("no data" != "bad data"):
//     zone-reaction (no uploaded milk-zone history exists — structural zero) and
//     yellowbox-break (solo box-breaks only exist behind the explicit YELLOWBOX_SOLO
//     opt-in, default off). Blocking them would dead-end user rule 5 (strong milk-zone
//     solo) and the YELLOWBOX_SOLO setting the moment they produce their first signal.
//   • Classes with FEWER THAN 50 HELD-OUT trades are too thin to judge: their verdict is
//     CARRIED FORWARD from the previous gate file and flagged lowConfidence
//     (statistical honesty — never silently block/allow on a thin sample).
//
// Generated 2026-08-12T20:46:46.980Z
// Stats source: scripts/fact-engine-backtest.ts two-stage walk-forward (2026-04-15..2026-08-12, split 2026-06-13: MC exits from the first half, verdicts from the held-out second half; 9785 ungated signals, symbol MES, ICT+fractal confirmations ON)
//   fact-engine@15m          n=372     PF=2.095  expectancy=+8.320  -> ALLOWED
//   fact-engine@1m           n=3692    PF=2.096  expectancy=+9.161  -> ALLOWED
//   fact-engine@5m           n=911     PF=2.014  expectancy=+8.570  -> ALLOWED
//   fact-engine@60m          n=125     PF=1.996  expectancy=+8.144  -> ALLOWED
//   vector-side-entry@15m    n=3       PF=999.000  expectancy=+23.333  -> ALLOWED  [LOW-CONF: carried forward]
//   vector-side-entry@1m     n=373     PF=2.357  expectancy=+7.183  -> ALLOWED
//   vector-side-entry@5m     n=28      PF=1.711  expectancy=+7.661  -> BLOCKED  [LOW-CONF: carried forward]
// Monte-Carlo calibrated exits (SL = p85 MAE of TP1-winners; TP1 = expectancy-max grid 4..30;
// TP2 = 2 x TP1). Grid payoff models the CANONICAL outcome semantics (2026-07-31,
// shared/outcome-resolver.ts): first touch decides (same-bar tie = SL-first); a TP1 win
// pays 2 x TP1 when TP2 is reached with no SL touch in between (the upgrade watch) and
// stays +TP1 otherwise — SL after TP1 never turns the win into a loss.
// [LOW-CONF] = the class's own window sample was n < 50:
//   fact-engine@15m          TP1=13.75  SL=23.00  (pool: its own trades)
//   fact-engine@1m           TP1=13.00  SL=24.50  (pool: its own trades)
//   fact-engine@5m           TP1=12.50  SL=24.25  (pool: its own trades)
//   fact-engine@60m          TP1=18.25  SL=24.50  (pool: its own trades)
//   vector-side-entry@15m    TP1=13.75  SL=23.00  (pool: all gated 15m trades)  [LOW-CONF]
//   vector-side-entry@1m     TP1=12.25  SL=27.25  (pool: its own trades)
//   vector-side-entry@5m     TP1=13.25  SL=24.50  (pool: all gated 5m trades)  [LOW-CONF]
// COMBO GATE (2026-07-29: "only take the historically winning fact-combinations"): a
// signal's COUNTED fact families form a canonical combo key (comboKeyOf — Vec/YB/ICT/Fr/
// FG/FP/Zone); verdicts below are judged on the held-out half's CLASS-GATED rows under the
// first-half class exits, at the SAME per-interval bars. "combo@interval" verdicts (n>=20)
// use THAT interval's bar; the all-interval "combo" fallback (n>=15) is evaluated at the
// CONSULTING interval's bar — its allowedByInterval map holds the per-interval verdicts
// (the summary allowed = ANY interval's bar passes; carried entries keep their carried
// verdict at every interval). Absent at both granularities = never blocked.
// A blocked combo suppresses EVEN >=3-counted-fact signals (the class-gate override does
// NOT bypass the combo gate); zone-reaction + ETH solo vector-side-entry are exempt:
//   FG+Fr+ICT+YB             n=21      PF=17.185  expectancy=+25.048  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   FG+Fr+Vec                n=44      PF=1.335  expectancy=+3.409  -> 1m:BLOCK 5m:BLOCK 15m:BLOCK 60m:BLOCK
//   FG+Fr+Vec@1m             n=37      PF=1.406  expectancy=+3.757  -> BLOCKED
//   FG+Fr+Vec+YB             n=47      PF=1.857  expectancy=+6.271  -> 1m:BLOCK 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   FG+Fr+Vec+YB@1m          n=36      PF=1.923  expectancy=+6.083  -> BLOCKED
//   FG+Fr+YB                 n=418     PF=1.878  expectancy=+7.907  -> 1m:BLOCK 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   FG+Fr+YB@15m             n=61      PF=1.313  expectancy=+3.295  -> BLOCKED
//   FG+Fr+YB@1m              n=230     PF=2.608  expectancy=+11.668  -> ALLOWED
//   FG+Fr+YB@5m              n=94      PF=1.170  expectancy=+2.082  -> BLOCKED
//   FG+Fr+YB@60m             n=33      PF=1.751  expectancy=+6.811  -> ALLOWED
//   FG+ICT+YB                n=17      PF=3.305  expectancy=+13.897  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   FG+Vec                   n=46      PF=1.546  expectancy=+4.332  -> 1m:BLOCK 5m:BLOCK 15m:BLOCK 60m:ALLOW
//   FG+Vec@1m                n=41      PF=1.397  expectancy=+3.213  -> BLOCKED
//   FG+Vec+YB                n=122     PF=2.623  expectancy=+7.936  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   FG+Vec+YB@1m             n=99      PF=2.984  expectancy=+8.242  -> ALLOWED
//   FG+YB                    n=287     PF=1.900  expectancy=+8.067  -> 1m:BLOCK 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   FG+YB@15m                n=28      PF=1.277  expectancy=+3.250  -> BLOCKED
//   FG+YB@1m                 n=188     PF=1.938  expectancy=+8.395  -> BLOCKED
//   FG+YB@5m                 n=60      PF=2.285  expectancy=+9.588  -> ALLOWED
//   FP+Fr+YB                 n=39      PF=11.093  expectancy=+20.769  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   FP+Fr+YB@5m              n=26      PF=13.875  expectancy=+22.779  -> ALLOWED
//   FP+YB                    n=23      PF=999.000  expectancy=+26.076  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   Fr+ICT+YB                n=128     PF=2.332  expectancy=+10.896  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   Fr+ICT+YB@1m             n=96      PF=2.143  expectancy=+10.359  -> ALLOWED
//   Fr+ICT+YB@5m             n=20      PF=2.676  expectancy=+11.375  -> ALLOWED
//   Fr+Vec                   n=127     PF=1.259  expectancy=+2.417  -> 1m:BLOCK 5m:BLOCK 15m:BLOCK 60m:BLOCK
//   Fr+Vec@1m                n=110     PF=1.485  expectancy=+3.920  -> BLOCKED
//   Fr+Vec+YB                n=105     PF=2.098  expectancy=+6.826  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   Fr+Vec+YB@1m             n=87      PF=2.126  expectancy=+6.606  -> ALLOWED
//   Fr+YB                    n=3634    PF=2.064  expectancy=+8.965  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   Fr+YB@15m                n=200     PF=2.347  expectancy=+9.440  -> ALLOWED
//   Fr+YB@1m                 n=2818    PF=2.084  expectancy=+9.173  -> ALLOWED
//   Fr+YB@5m                 n=553     PF=1.886  expectancy=+7.837  -> ALLOWED
//   Fr+YB@60m                n=63      PF=2.068  expectancy=+8.083  -> ALLOWED
//   ICT+YB                   n=178     PF=2.720  expectancy=+12.183  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   ICT+YB@1m                n=146     PF=2.680  expectancy=+12.091  -> ALLOWED
//   ICT+YB@5m                n=21      PF=3.000  expectancy=+13.143  -> ALLOWED
//   Vec                      n=10      PF=2.431  expectancy=+7.725  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW  [LOW-CONF: carried forward]
//   Vec@1m                   n=10      PF=2.431  expectancy=+7.725  -> ALLOWED  [LOW-CONF: carried forward]
//   Vec@5m                   n=0       PF=0.000  expectancy=+0.000  -> ALLOWED  [LOW-CONF: carried forward]
//   Vec+YB                   n=187     PF=2.231  expectancy=+7.215  -> 1m:ALLOW 5m:ALLOW 15m:ALLOW 60m:ALLOW
//   Vec+YB@1m                n=118     PF=1.802  expectancy=+4.801  -> BLOCKED
//   Vec+YB@5m                n=51      PF=2.967  expectancy=+11.505  -> ALLOWED
// PER-COMBO Monte-Carlo exits (mission 2026-07-29 — "5m and 15m fire only their most
// optimized, winning trades"): gate-ALLOWED combos with >=30 of their own gated-window
// trades grid-search their OWN TP1 (4..30, SL = p85 MAE of TP1-winners, >=30-winners rule);
// 15..29 own trades pool with the same-interval allowed-combo trades; fewer -> the
// class exit governs. Engine resolution: caller-explicit exit > combo exit > class exit >
// provisional (zone/yellowbox TP1 anchors keep priority inside computeExit; zone-reaction +
// vector-side-entry stay class-exited). [LOW-CONF] = own sample n < 50:
//   FG+Fr+ICT+YB@1m          TP1=13.00  SL=24.50  (n=26, pool: same-interval allowed-combo trades (combo n=26 in 15..29))  [LOW-CONF]
//   FG+Fr+YB@1m              TP1=14.00  SL=22.50  (n=497, pool: its own trades)
//   FG+Fr+YB@60m             TP1=19.00  SL=17.25  (n=56, pool: its own trades)
//   FG+ICT+YB@1m             TP1=11.00  SL=22.75  (n=34, pool: its own trades)  [LOW-CONF]
//   FG+Vec+YB@1m             TP1=4.50  SL=6.00  (n=59, pool: its own trades)
//   FG+Vec+YB@5m             TP1=12.50  SL=24.25  (n=18, pool: same-interval allowed-combo trades (combo n=18 in 15..29))  [LOW-CONF]
//   FG+YB@5m                 TP1=13.25  SL=24.75  (n=121, pool: its own trades)
//   FG+YB@60m                TP1=18.25  SL=24.50  (n=25, pool: same-interval allowed-combo trades (combo n=25 in 15..29))  [LOW-CONF]
//   FP+Fr+YB@15m             TP1=13.75  SL=23.00  (n=23, pool: same-interval allowed-combo trades (combo n=23 in 15..29))  [LOW-CONF]
//   FP+Fr+YB@5m              TP1=24.25  SL=21.75  (n=53, pool: its own trades)
//   FP+YB@5m                 TP1=22.00  SL=19.50  (n=44, pool: its own trades)  [LOW-CONF]
//   Fr+ICT+YB@15m            TP1=13.75  SL=23.00  (n=20, pool: same-interval allowed-combo trades (combo n=20 in 15..29))  [LOW-CONF]
//   Fr+ICT+YB@1m             TP1=16.75  SL=29.25  (n=158, pool: its own trades)
//   Fr+ICT+YB@5m             TP1=11.50  SL=18.00  (n=40, pool: its own trades)  [LOW-CONF]
//   Fr+Vec+YB@1m             TP1=8.50  SL=15.50  (n=62, pool: its own trades)
//   Fr+Vec+YB@5m             TP1=12.50  SL=24.25  (n=16, pool: same-interval allowed-combo trades (combo n=16 in 15..29))  [LOW-CONF]
//   Fr+YB@15m                TP1=11.25  SL=21.75  (n=377, pool: its own trades)
//   Fr+YB@1m                 TP1=13.25  SL=25.00  (n=5002, pool: its own trades)
//   Fr+YB@5m                 TP1=11.25  SL=24.00  (n=1065, pool: its own trades)
//   Fr+YB@60m                TP1=10.75  SL=20.00  (n=109, pool: its own trades)
//   ICT+YB@1m                TP1=16.75  SL=24.75  (n=258, pool: its own trades)
//   ICT+YB@5m                TP1=12.25  SL=24.00  (n=39, pool: its own trades)  [LOW-CONF]
//   Vec+YB@15m               TP1=13.75  SL=23.00  (n=22, pool: same-interval allowed-combo trades (combo n=22 in 15..29))  [LOW-CONF]
//   Vec+YB@5m                TP1=17.50  SL=26.50  (n=84, pool: its own trades)
// ═════════════════════════════════════════════════════════════════════════════

/** One interval's gate bar: PF >= MIN_PF AND expectancy > MIN_EXPECTANCY_PTS (pts/trade). */
export interface GateBar {
  MIN_PF: number;             // class must show profit factor >= this ...
  MIN_EXPECTANCY_PTS: number; // ... AND expectancy strictly > this (pts/trade)
}
export interface GateRule {
  /** PER-INTERVAL GATE BARS (user-chosen 2026-07-31 from the per-interval gate-bar menu,
   *  scripts/gate-bar-menu-by-interval.ts): every class and "<combo>@<interval>" verdict is
   *  judged at ITS OWN interval's bar; all-interval fallback combo verdicts are evaluated per
   *  CONSULTING interval (GateClassStat.allowedByInterval). */
  perInterval: Record<string, GateBar>;
  MIN_FACTS_OVERRIDE: number; // >= this many COUNTED facts bypasses the class gate
}
export interface GateClassStat {
  n: number;
  pf: number;
  expectancy: number;
  winRate: number;
  allowed: boolean;
  /** ALL-INTERVAL fallback combo entries only (PER-INTERVAL GATE BARS 2026-07-31): the
   *  verdict at EACH consulting interval's bar — comboGateAllows consults this map FIRST;
   *  the summary `allowed` (true when ANY interval's bar passes) is only the legacy
   *  fallback for configs predating this field. Carried (lowConfidence) entries replicate
   *  the carried verdict at every interval — thin data never flips at any bar. */
  allowedByInterval?: Record<string, boolean>;
  /** True when the verdict rests on a thin sample (n < 50 in the reporting window): the
   *  `allowed` flag is CARRIED FORWARD from the previous full-history verdict (see `note`)
   *  rather than judged on the thin window stats. */
  lowConfidence?: boolean;
  note?: string;
}
/** Monte-Carlo calibrated exit distances for one class (pts). TP2 stays 2 x TP1 (user rule);
 *  `pool` names the sample the calibration came from when the class itself had n < 100. */
export interface ClassExit {
  tp1: number;
  sl: number;
  n: number;
  pool: string;
  /** True when the class's own sample in the reporting window was n < 50 — the calibration
   *  rests on pooled/thin data; treat the exits with caution. */
  lowConfidence?: boolean;
}
export interface QualityGateData {
  generatedAt: string;
  source: string;
  rule: GateRule;
  multiFact: { n: number; pf: number; expectancy: number };
  classes: Record<string, GateClassStat>;
  exitByClass: Record<string, ClassExit>;
  /** COMBO GATE (2026-07-29): verdicts per canonical fact-FAMILY combination (comboKeyOf), at
   *  two granularities — "<combo>@<interval>" (needs n>=20 held-out class-gated rows) and
   *  "<combo>" all-interval fallback (needs n>=15). A combo key absent at BOTH granularities is
   *  never blocked (class gate alone governs — thin data blocks nothing). Optional so older
   *  synthetic/neutral configs stay valid. */
  comboClasses?: Record<string, GateClassStat>;
  /** PER-COMBO Monte-Carlo exits (2026-07-29 — "5m/15m fire only their most optimized trades"):
   *  calibrated TP1/SL for gate-ALLOWED fact combinations with enough of their own trades,
   *  keyed "<combo>@<interval>" ONLY (no all-interval fallback — exit distances are
   *  interval-scale-sensitive). Engine resolution priority: caller-explicit exit > combo exit >
   *  class exit > provisional; zone/yellowbox TP1 anchors keep their priority inside
   *  computeExit. zone-reaction + vector-side-entry are exempt (structural rules — class exits
   *  only). Optional so older synthetic/neutral configs stay valid. */
  exitByCombo?: Record<string, ClassExit>;
}

export const QUALITY_GATE: QualityGateData = {
  "generatedAt": "2026-08-18T03:12:07.666Z",
  "source": "scripts/fact-engine-backtest.ts two-stage walk-forward (2026-04-15..2026-08-12, split 2026-06-13: MC exits from the first half, verdicts from the held-out second half; 9785 ungated signals, symbol MES, ICT+fractal confirmations ON) | HAND-CALIBRATED 2026-08-13 by the best-program ship (15m combo blocks + 10.5/26 exits) — review the next weekly regen against these verdicts before accepting it",
  "rule": {
    "perInterval": {
      "1m": {
        "MIN_PF": 2,
        "MIN_EXPECTANCY_PTS": 5
      },
      "5m": {
        "MIN_PF": 1.75,
        "MIN_EXPECTANCY_PTS": 4
      },
      "15m": {
        "MIN_PF": 1.75,
        "MIN_EXPECTANCY_PTS": 4
      },
      "60m": {
        "MIN_PF": 1.5,
        "MIN_EXPECTANCY_PTS": 3
      }
    },
    "MIN_FACTS_OVERRIDE": 3
  },
  "multiFact": {
    "n": 2369,
    "pf": 2.031,
    "expectancy": 8.393
  },
  "classes": {
    "fact-engine@15m": {
      "n": 372,
      "pf": 2.095,
      "expectancy": 8.32,
      "winRate": 0.707,
      "allowed": true,
      "note": "walk-forward: exits TP1 14/SL 32.75 from the first half (270 own trades, pool: its own first-half trades); judged on the held-out second half 2026-06-13..2026-08-12 (n=372) at the 15m bar (PF>=1.75 & EXP>4)"
    },
    "fact-engine@1m": {
      "n": 3692,
      "pf": 2.096,
      "expectancy": 9.161,
      "winRate": 0.69,
      "allowed": true,
      "note": "walk-forward: exits TP1 17.5/SL 35.75 from the first half (2798 own trades, pool: its own first-half trades); judged on the held-out second half 2026-06-13..2026-08-12 (n=3692) at the 1m bar (PF>=2 & EXP>5)"
    },
    "fact-engine@5m": {
      "n": 911,
      "pf": 2.014,
      "expectancy": 8.57,
      "winRate": 0.681,
      "allowed": true,
      "note": "walk-forward: exits TP1 17.25/SL 34.25 from the first half (753 own trades, pool: its own first-half trades); judged on the held-out second half 2026-06-13..2026-08-12 (n=911) at the 5m bar (PF>=1.75 & EXP>4)"
    },
    "fact-engine@60m": {
      "n": 125,
      "pf": 1.996,
      "expectancy": 8.144,
      "winRate": 0.688,
      "allowed": true,
      "note": "walk-forward: exits TP1 18.25/SL 32.5 from the first half (88 own trades, pool: its own first-half trades (small sample kept — interval-scale faithful)); judged on the held-out second half 2026-06-13..2026-08-12 (n=125) at the 60m bar (PF>=1.5 & EXP>3)"
    },
    "vector-side-entry@15m": {
      "n": 3,
      "pf": 999,
      "expectancy": 23.333,
      "winRate": 1,
      "allowed": true,
      "lowConfidence": true,
      "note": "carried forward (insufficient held-out sample, n=3 < 50): previous gate verdict ALLOWED (n=3, PF=999, expectancy=24.333); walk-forward: exits TP1 14/SL 33 from the first half (4 own trades, pool: all first-half 15m trades); judged on the held-out second half 2026-06-13..2026-08-12 (n=3) at the 15m bar (PF>=1.75 & EXP>4)"
    },
    "vector-side-entry@1m": {
      "n": 373,
      "pf": 2.357,
      "expectancy": 7.183,
      "winRate": 0.791,
      "allowed": true,
      "note": "walk-forward: exits TP1 8.75/SL 27 from the first half (291 own trades, pool: its own first-half trades); judged on the held-out second half 2026-06-13..2026-08-12 (n=373) at the 1m bar (PF>=2 & EXP>5)"
    },
    "vector-side-entry@5m": {
      "n": 28,
      "pf": 1.711,
      "expectancy": 7.661,
      "winRate": 0.679,
      "allowed": false,
      "lowConfidence": true,
      "note": "carried forward (insufficient held-out sample, n=28 < 50): previous gate verdict BLOCKED (n=28, PF=1.814, expectancy=9.938); walk-forward: exits TP1 18.25/SL 36 from the first half (16 own trades, pool: all first-half 5m trades); judged on the held-out second half 2026-06-13..2026-08-12 (n=28) at the 5m bar (PF>=1.75 & EXP>4)"
    }
  },
  "exitByClass": {
    "fact-engine@15m": {
      "tp1": 10.5,
      "sl": 26,
      "n": 522,
      "pool": "best-program lab 2026-08-13: valid-era Pareto knee on the blocked 15m set, realistic fills (86.9% win, +4.65/tr net)"
    },
    "fact-engine@1m": {
      "tp1": 13,
      "sl": 24.5,
      "n": 6111,
      "pool": "its own trades"
    },
    "fact-engine@5m": {
      "tp1": 12.5,
      "sl": 24.25,
      "n": 1550,
      "pool": "its own trades"
    },
    "fact-engine@60m": {
      "tp1": 18.25,
      "sl": 24.5,
      "n": 212,
      "pool": "its own trades"
    },
    "vector-side-entry@15m": {
      "tp1": 10.5,
      "sl": 26,
      "n": 7,
      "pool": "best-program lab 2026-08-13: valid-era Pareto knee on the blocked 15m set, realistic fills (86.9% win, +4.65/tr net)",
      "lowConfidence": true
    },
    "vector-side-entry@1m": {
      "tp1": 12.25,
      "sl": 27.25,
      "n": 686,
      "pool": "its own trades"
    },
    "vector-side-entry@5m": {
      "tp1": 13.25,
      "sl": 24.5,
      "n": 33,
      "pool": "all gated 5m trades",
      "lowConfidence": true
    }
  },
  "comboClasses": {
    "FG+Fr+Vec@1m": {
      "n": 37,
      "pf": 1.406,
      "expectancy": 3.757,
      "winRate": 0.676,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=37); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "FG+Fr+Vec+YB@1m": {
      "n": 36,
      "pf": 1.923,
      "expectancy": 6.083,
      "winRate": 0.694,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=36); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "FG+Fr+YB@15m": {
      "n": 61,
      "pf": 1.313,
      "expectancy": 3.295,
      "winRate": 0.623,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=61); judged at the 15m bar (PF>=1.75 & EXP>4)"
    },
    "FG+Fr+YB@1m": {
      "n": 230,
      "pf": 2.608,
      "expectancy": 11.668,
      "winRate": 0.739,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=230); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "FG+Fr+YB@5m": {
      "n": 94,
      "pf": 1.17,
      "expectancy": 2.082,
      "winRate": 0.564,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=94); judged at the 5m bar (PF>=1.75 & EXP>4)"
    },
    "FG+Fr+YB@60m": {
      "n": 33,
      "pf": 1.751,
      "expectancy": 6.811,
      "winRate": 0.636,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=33); judged at the 60m bar (PF>=1.5 & EXP>3)"
    },
    "FG+Vec@1m": {
      "n": 41,
      "pf": 1.397,
      "expectancy": 3.213,
      "winRate": 0.634,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=41); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "FG+Vec+YB@1m": {
      "n": 99,
      "pf": 2.984,
      "expectancy": 8.242,
      "winRate": 0.747,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=99); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "FG+YB@15m": {
      "n": 28,
      "pf": 1.277,
      "expectancy": 3.25,
      "winRate": 0.607,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=28); judged at the 15m bar (PF>=1.75 & EXP>4)"
    },
    "FG+YB@1m": {
      "n": 188,
      "pf": 1.938,
      "expectancy": 8.395,
      "winRate": 0.686,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=188); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "FG+YB@5m": {
      "n": 60,
      "pf": 2.285,
      "expectancy": 9.588,
      "winRate": 0.7,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=60); judged at the 5m bar (PF>=1.75 & EXP>4)"
    },
    "FP+Fr+YB@5m": {
      "n": 26,
      "pf": 13.875,
      "expectancy": 22.779,
      "winRate": 0.808,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=26); judged at the 5m bar (PF>=1.75 & EXP>4)"
    },
    "Fr+ICT+YB@1m": {
      "n": 96,
      "pf": 2.143,
      "expectancy": 10.359,
      "winRate": 0.688,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=96); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "Fr+ICT+YB@5m": {
      "n": 20,
      "pf": 2.676,
      "expectancy": 11.375,
      "winRate": 0.7,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=20); judged at the 5m bar (PF>=1.75 & EXP>4)"
    },
    "Fr+Vec@1m": {
      "n": 110,
      "pf": 1.485,
      "expectancy": 3.92,
      "winRate": 0.682,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=110); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "Fr+Vec+YB@1m": {
      "n": 87,
      "pf": 2.126,
      "expectancy": 6.606,
      "winRate": 0.736,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=87); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "Fr+YB@15m": {
      "n": 200,
      "pf": 2.347,
      "expectancy": 9.44,
      "winRate": 0.745,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=200); judged at the 15m bar (PF>=1.75 & EXP>4) | BEST-PROGRAM OVERRIDE 2026-08-13 (user-approved 'do your recommendations'): blocked on the executable TP1-only record — negative on BOTH the lab reference-geometry basis (train era 2025-06..2026-04) and the as-calibrated rebased book. The pre-override record-convention stats are retired; see LEARNINGS."
    },
    "Fr+YB@1m": {
      "n": 2818,
      "pf": 2.084,
      "expectancy": 9.173,
      "winRate": 0.695,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=2818); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "Fr+YB@5m": {
      "n": 553,
      "pf": 1.886,
      "expectancy": 7.837,
      "winRate": 0.678,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=553); judged at the 5m bar (PF>=1.75 & EXP>4)"
    },
    "Fr+YB@60m": {
      "n": 63,
      "pf": 2.068,
      "expectancy": 8.083,
      "winRate": 0.714,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=63); judged at the 60m bar (PF>=1.5 & EXP>3)"
    },
    "ICT+YB@1m": {
      "n": 146,
      "pf": 2.68,
      "expectancy": 12.091,
      "winRate": 0.705,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=146); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "ICT+YB@5m": {
      "n": 21,
      "pf": 3,
      "expectancy": 13.143,
      "winRate": 0.762,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=21); judged at the 5m bar (PF>=1.75 & EXP>4)"
    },
    "Vec+YB@1m": {
      "n": 118,
      "pf": 1.802,
      "expectancy": 4.801,
      "winRate": 0.695,
      "allowed": false,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=118); judged at the 1m bar (PF>=2 & EXP>5)"
    },
    "Vec+YB@5m": {
      "n": 51,
      "pf": 2.967,
      "expectancy": 11.505,
      "winRate": 0.686,
      "allowed": true,
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=51); judged at the 5m bar (PF>=1.75 & EXP>4)"
    },
    "FG+Fr+ICT+YB": {
      "n": 21,
      "pf": 17.185,
      "expectancy": 25.048,
      "winRate": 0.952,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=21); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "FG+Fr+Vec": {
      "n": 44,
      "pf": 1.335,
      "expectancy": 3.409,
      "winRate": 0.659,
      "allowed": false,
      "allowedByInterval": {
        "1m": false,
        "5m": false,
        "15m": false,
        "60m": false
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=44); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "FG+Fr+Vec+YB": {
      "n": 47,
      "pf": 1.857,
      "expectancy": 6.271,
      "winRate": 0.681,
      "allowed": true,
      "allowedByInterval": {
        "1m": false,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=47); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "FG+Fr+YB": {
      "n": 418,
      "pf": 1.878,
      "expectancy": 7.907,
      "winRate": 0.675,
      "allowed": true,
      "allowedByInterval": {
        "1m": false,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=418); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "FG+ICT+YB": {
      "n": 17,
      "pf": 3.305,
      "expectancy": 13.897,
      "winRate": 0.824,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=17); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "FG+Vec": {
      "n": 46,
      "pf": 1.546,
      "expectancy": 4.332,
      "winRate": 0.652,
      "allowed": true,
      "allowedByInterval": {
        "1m": false,
        "5m": false,
        "15m": false,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=46); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "FG+Vec+YB": {
      "n": 122,
      "pf": 2.623,
      "expectancy": 7.936,
      "winRate": 0.746,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=122); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "FG+YB": {
      "n": 287,
      "pf": 1.9,
      "expectancy": 8.067,
      "winRate": 0.679,
      "allowed": true,
      "allowedByInterval": {
        "1m": false,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=287); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "FP+Fr+YB": {
      "n": 39,
      "pf": 11.093,
      "expectancy": 20.769,
      "winRate": 0.821,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=39); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "FP+YB": {
      "n": 23,
      "pf": 999,
      "expectancy": 26.076,
      "winRate": 1,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=23); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "Fr+ICT+YB": {
      "n": 128,
      "pf": 2.332,
      "expectancy": 10.896,
      "winRate": 0.695,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=128); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "Fr+Vec": {
      "n": 127,
      "pf": 1.259,
      "expectancy": 2.417,
      "winRate": 0.646,
      "allowed": false,
      "allowedByInterval": {
        "1m": false,
        "5m": false,
        "15m": false,
        "60m": false
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=127); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "Fr+Vec+YB": {
      "n": 105,
      "pf": 2.098,
      "expectancy": 6.826,
      "winRate": 0.714,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=105); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "Fr+YB": {
      "n": 3634,
      "pf": 2.064,
      "expectancy": 8.965,
      "winRate": 0.695,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=3634); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "ICT+YB": {
      "n": 178,
      "pf": 2.72,
      "expectancy": 12.183,
      "winRate": 0.708,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=178); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "Vec+YB": {
      "n": 187,
      "pf": 2.231,
      "expectancy": 7.215,
      "winRate": 0.69,
      "allowed": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=187); all-interval fallback granularity — verdict evaluated at the CONSULTING interval's bar (allowedByInterval; summary allowed = ANY interval's bar passes)"
    },
    "Vec@1m": {
      "n": 10,
      "pf": 2.431,
      "expectancy": 7.725,
      "winRate": 0.8,
      "allowed": true,
      "lowConfidence": true,
      "note": "carried forward (insufficient held-out sample, n=10 < 20): previous combo verdict ALLOWED (n=10, PF=42, expectancy=21.525); combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=10)"
    },
    "Vec": {
      "n": 10,
      "pf": 2.431,
      "expectancy": 7.725,
      "winRate": 0.8,
      "allowed": true,
      "lowConfidence": true,
      "allowedByInterval": {
        "1m": true,
        "5m": true,
        "15m": true,
        "60m": true
      },
      "note": "carried forward (insufficient held-out sample, n=10 < 15): previous combo verdict ALLOWED (n=10, PF=42, expectancy=21.525); combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=10)"
    },
    "Vec@5m": {
      "n": 0,
      "pf": 0,
      "expectancy": 0,
      "winRate": 0,
      "allowed": true,
      "lowConfidence": true,
      "note": "carried forward (insufficient held-out sample, n=0 < 20): previous combo verdict ALLOWED (n=0, PF=0, expectancy=0); combo gate: judged on the held-out CLASS-GATED rows 2026-06-13..2026-08-12 under the first-half class exits (n=0)"
    },
    "Vec+YB@15m": {
      "n": 49,
      "winRate": 0.653,
      "pf": 0.8,
      "expectancy": -2.6,
      "allowed": false,
      "note": "BEST-PROGRAM OVERRIDE 2026-08-13 (user-approved 'do your recommendations'): blocked on the executable TP1-only record — negative on BOTH the lab reference-geometry basis (train era 2025-06..2026-04) and the as-calibrated rebased book. The pre-override record-convention stats are retired; see LEARNINGS."
    },
    "Fr+Vec+YB@15m": {
      "n": 34,
      "winRate": 0.618,
      "pf": 0.71,
      "expectancy": -3.58,
      "allowed": false,
      "note": "BEST-PROGRAM OVERRIDE 2026-08-13 (user-approved 'do your recommendations'): blocked on the executable TP1-only record — negative on BOTH the lab reference-geometry basis (train era 2025-06..2026-04) and the as-calibrated rebased book. The pre-override record-convention stats are retired; see LEARNINGS."
    },
    "ICT+YB@15m": {
      "n": 30,
      "winRate": 0.733,
      "pf": 0.9,
      "expectancy": -1.61,
      "allowed": false,
      "note": "BEST-PROGRAM OVERRIDE 2026-08-13 (user-approved 'do your recommendations'): blocked on the executable TP1-only record — negative on BOTH the lab reference-geometry basis (train era 2025-06..2026-04) and the as-calibrated rebased book. The pre-override record-convention stats are retired; see LEARNINGS."
    },
    "Fr+ICT+YB@15m": {
      "n": 24,
      "winRate": 0.708,
      "pf": 0.94,
      "expectancy": -1.43,
      "allowed": false,
      "note": "BEST-PROGRAM OVERRIDE 2026-08-13 (user-approved 'do your recommendations'): blocked on the executable TP1-only record — negative on BOTH the lab reference-geometry basis (train era 2025-06..2026-04) and the as-calibrated rebased book. The pre-override record-convention stats are retired; see LEARNINGS."
    },
    "FG+Fr+Vec+YB@15m": {
      "n": 17,
      "winRate": 0.647,
      "pf": 0.73,
      "expectancy": -3.18,
      "allowed": false,
      "note": "BEST-PROGRAM OVERRIDE 2026-08-13 (user-approved 'do your recommendations'): blocked on the executable TP1-only record — negative on BOTH the lab reference-geometry basis (train era 2025-06..2026-04) and the as-calibrated rebased book. The pre-override record-convention stats are retired; see LEARNINGS."
    }
  },
  "exitByCombo": {
    "FG+Fr+ICT+YB@1m": {
      "tp1": 13,
      "sl": 24.5,
      "n": 26,
      "pool": "same-interval allowed-combo trades (combo n=26 in 15..29)",
      "lowConfidence": true
    },
    "FG+Fr+YB@1m": {
      "tp1": 14,
      "sl": 22.5,
      "n": 497,
      "pool": "its own trades"
    },
    "FG+Fr+YB@60m": {
      "tp1": 19,
      "sl": 17.25,
      "n": 56,
      "pool": "its own trades"
    },
    "FG+ICT+YB@1m": {
      "tp1": 11,
      "sl": 22.75,
      "n": 34,
      "pool": "its own trades",
      "lowConfidence": true
    },
    "FG+Vec+YB@1m": {
      "tp1": 4.5,
      "sl": 6,
      "n": 59,
      "pool": "its own trades"
    },
    "FG+Vec+YB@5m": {
      "tp1": 12.5,
      "sl": 24.25,
      "n": 18,
      "pool": "same-interval allowed-combo trades (combo n=18 in 15..29)",
      "lowConfidence": true
    },
    "FG+YB@5m": {
      "tp1": 13.25,
      "sl": 24.75,
      "n": 121,
      "pool": "its own trades"
    },
    "FG+YB@60m": {
      "tp1": 18.25,
      "sl": 24.5,
      "n": 25,
      "pool": "same-interval allowed-combo trades (combo n=25 in 15..29)",
      "lowConfidence": true
    },
    "FP+Fr+YB@15m": {
      "tp1": 13.75,
      "sl": 23,
      "n": 23,
      "pool": "same-interval allowed-combo trades (combo n=23 in 15..29)",
      "lowConfidence": true
    },
    "FP+Fr+YB@5m": {
      "tp1": 24.25,
      "sl": 21.75,
      "n": 53,
      "pool": "its own trades"
    },
    "FP+YB@5m": {
      "tp1": 22,
      "sl": 19.5,
      "n": 44,
      "pool": "its own trades",
      "lowConfidence": true
    },
    "Fr+ICT+YB@15m": {
      "tp1": 13.75,
      "sl": 23,
      "n": 20,
      "pool": "same-interval allowed-combo trades (combo n=20 in 15..29)",
      "lowConfidence": true
    },
    "Fr+ICT+YB@1m": {
      "tp1": 16.75,
      "sl": 29.25,
      "n": 158,
      "pool": "its own trades"
    },
    "Fr+ICT+YB@5m": {
      "tp1": 11.5,
      "sl": 18,
      "n": 40,
      "pool": "its own trades",
      "lowConfidence": true
    },
    "Fr+Vec+YB@1m": {
      "tp1": 8.5,
      "sl": 15.5,
      "n": 62,
      "pool": "its own trades"
    },
    "Fr+Vec+YB@5m": {
      "tp1": 12.5,
      "sl": 24.25,
      "n": 16,
      "pool": "same-interval allowed-combo trades (combo n=16 in 15..29)",
      "lowConfidence": true
    },
    "Fr+YB@15m": {
      "tp1": 11.25,
      "sl": 21.75,
      "n": 377,
      "pool": "its own trades"
    },
    "Fr+YB@1m": {
      "tp1": 13.25,
      "sl": 25,
      "n": 5002,
      "pool": "its own trades"
    },
    "Fr+YB@5m": {
      "tp1": 11.25,
      "sl": 24,
      "n": 1065,
      "pool": "its own trades"
    },
    "Fr+YB@60m": {
      "tp1": 10.75,
      "sl": 20,
      "n": 109,
      "pool": "its own trades"
    },
    "ICT+YB@1m": {
      "tp1": 16.75,
      "sl": 24.75,
      "n": 258,
      "pool": "its own trades"
    },
    "ICT+YB@5m": {
      "tp1": 12.25,
      "sl": 24,
      "n": 39,
      "pool": "its own trades",
      "lowConfidence": true
    },
    "Vec+YB@15m": {
      "tp1": 13.75,
      "sl": 23,
      "n": 22,
      "pool": "same-interval allowed-combo trades (combo n=22 in 15..29)",
      "lowConfidence": true
    },
    "Vec+YB@5m": {
      "tp1": 17.5,
      "sl": 26.5,
      "n": 84,
      "pool": "its own trades"
    }
  }
};

export function classKey(signalType: string, interval: string): string {
  return `${signalType}@${interval}`;
}

/** The final firing filter. A blocked class emits NOTHING (not even a note).
 *  - >=3 counted agreeing facts always pass (any interval, any session);
 *  - a class absent from the stats map is never blocked (no data != bad data — this is what
 *    keeps zone-reaction and yellowbox-break, both structural zeros historically, alive). */
export function qualityGateAllows(
  signalType: string,
  interval: string,
  countedFacts: number,
  data: QualityGateData = QUALITY_GATE,
): boolean {
  if (countedFacts >= data.rule.MIN_FACTS_OVERRIDE) return true;
  const cls = data.classes[classKey(signalType, interval)];
  if (!cls) return true;
  return cls.allowed;
}

// ── COMBO GATE (2026-07-29): only historically winning FACT COMBINATIONS may fire ────────────
/** Fact strategy → family code. The combo key is the sorted de-duplicated set of family codes
 *  over a signal's COUNTED facts (label-notes excluded — they are annotations, not evidence).
 *  backtestable:false facts (PML/TML live-only levels) are ALSO excluded: no backtest can ever
 *  judge a combo containing them, so live-only evidence must not move a signal into an
 *  unjudged combo class (it would silently bypass a blocked base combo). */
export const FACT_FAMILY: Record<string, string> = {
  vector: "Vec", yellowbox: "YB", ict: "ICT", fractal: "Fr",
  fractalGeo: "FG", footprint: "FP", zone: "Zone", moneyline: "ML",
};
/** Structural fact shape for combo-key computation (avoids importing the engine's Fact type —
 *  quality-gate.ts must stay import-free; fact-engine.ts imports THIS module). */
export interface ComboFactLike { strategy: string; counted: boolean; backtestable?: boolean }
/** Canonical combo key, e.g. "Fr+Vec+YB". Engine and harness MUST both use this helper —
 *  any drift in key construction silently desynchronizes live gating from the backtest. */
export function comboKeyOf(facts: ComboFactLike[]): string {
  const fams = new Set<string>();
  for (const f of facts) {
    if (!f.counted) continue;              // label-note facts never form the combo
    if (f.backtestable === false) continue; // live-only evidence (see FACT_FAMILY note)
    fams.add(FACT_FAMILY[f.strategy] ?? f.strategy);
  }
  return [...fams].sort().join("+");
}
/** The combo firing filter — consulted AFTER the class gate, and (unlike the class gate) it
 *  applies EVEN to >=3-counted-fact signals: the multi-fact override exists to admit rich
 *  confluence, but a combination that historically LOSES (e.g. Fr+ICT+Vec+YB, a 4-fact loser)
 *  must stay blocked regardless of fact count. Lookup: "<combo>@<interval>" first, then the
 *  all-interval "<combo>" — whose verdict is PER CONSULTING INTERVAL (allowedByInterval,
 *  per-interval gate bars 2026-07-31; the summary `allowed` covers older configs); absent at
 *  both granularities → allowed (thin data blocks nothing).
 *  Exemptions live in the engine: zone-reaction (strong milk-zone solo) and ETH solo
 *  vector-side-entry are structural rules with zero backtest data — never combo-gated. */
export function comboGateAllows(
  combo: string,
  interval: string,
  data: QualityGateData = QUALITY_GATE,
): boolean {
  const cc = data.comboClasses;
  if (!cc || !combo) return true;
  const atIv = cc[`${combo}@${interval}`];
  if (atIv) return atIv.allowed;
  const all = cc[combo];
  if (all) return all.allowedByInterval?.[interval] ?? all.allowed;
  return true;
}

/** Monte-Carlo exit override for a class, or null to use the engine's provisional defaults. */
export function exitOverrideFor(
  signalType: string,
  interval: string,
  data: QualityGateData = QUALITY_GATE,
): ClassExit | null {
  return data.exitByClass[classKey(signalType, interval)] ?? null;
}

/** PER-COMBO Monte-Carlo exit override ("<combo>@<interval>" only), or null when the combo has
 *  no calibration of its own — the class exit (exitOverrideFor) then governs. */
export function comboExitOverrideFor(
  combo: string,
  interval: string,
  data: QualityGateData = QUALITY_GATE,
): ClassExit | null {
  if (!combo) return null;
  return data.exitByCombo?.[`${combo}@${interval}`] ?? null;
}
